local Color, c, Group, g, style = require("colorbuddy").setup()
-- local _, c, Group, g, style = require("colorbuddy").setup()
local italics = require("colors.utils").italics

Group.new("FloatBorder", c.RedBright, c.none, style.NONE)
Group.new("NormalFloat", c.White, c.none, style.NONE)

-----------------------------
--     LSP Highlighting    --
-----------------------------
Group.new("DiagnosticError", c.Error, c.none, style.NONE)
Group.new("DiagnosticWarning", c.Warning, c.none, style.NONE)
Group.new("DiagnosticInformation", c.Information, c.none, style.NONE)
Group.new("DiagnosticHint", c.Hint, c.none, style.NONE)

-----------------------
--     WHICH KEY     --
-----------------------
Group.new("WhichKey", c.Blue, c.none, style.bold)
Group.new("WhichKeyFloat", c.White, c.Black, style.NONE)
Group.new("WhichKeyGroup", c.Yellow, c.none, style.bold)
Group.new("WhichKeyDesc", c.Hint, c.none, style.NONE)

-----------------------
--    LightSpeed     --
-----------------------
Group.new("LightSpeedLabel", c.Green, c.none, style.bold)
Group.new("LightSpeedShortcut", c.Pink, c.none, style.bold)
Group.new("LightSpeedLabelOverlapped", c.White, c.Green, style.NONE)

----------------------
-- Vim Editor Color --
----------------------
Group.new("Boolean", c.hue_6, c.none, style.NONE)
Group.new("Character", c.hue_4, c.none, style.NONE)
Group.new("ColorColumn", c.none, c.syntax_cursor, style.NONE)
Group.new("Comment", c.Gray, c.none, italics)
Group.new("Conceal", c.Gray:dark(), c.syntax_bg, style.NONE)
Group.new("Conditional", c.hue_3, c.none, style.NONE)
Group.new("Constant", c.hue_4, c.none, style.NONE)
Group.new("Cursor", c.none, c.syntax_accent, style.NONE)
Group.new("CursorColumn", c.none, c.syntax_cursor, style.NONE)
Group.new("CursorIM", c.none, c.none, style.NONE)
Group.new("CursorLine", c.none, c.syntax_cursor, style.NONE)
Group.new("CursorLineNr", c.White, c.syntax_cursor, style.NONE)
Group.new("Debug", c.none, c.none, style.NONE)
Group.new("Define", c.hue_3, c.none, style.NONE)
Group.new("Delimiter", c.none, c.none, style.NONE)
Group.new("Directory", c.hue_2, c.none, style.NONE)
Group.new("Error", c.hue_5, c.Gray, style.bold)
Group.new("ErrorMsg", c.hue_5, c.none, style.NONE)
Group.new("Exception", c.hue_3, c.none, style.NONE)
Group.new("Float", c.hue_6, c.none, style.NONE)
Group.new("FoldColumn", c.Gray, c.syntax_cursor, style.NONE)
Group.new("Folded", c.special_grey, c.none, style.NONE)
Group.new("Function", c.hue_2, c.none, style.NONE)
Group.new("Identifier", c.hue_5, c.none, style.NONE)
Group.new("Ignore", c.none, c.none, style.NONE)
Group.new("IncSearch", c.syntax_bg, c.hue_2, style.NONE)
Group.new("Include", c.hue_2, c.none, style.NONE)
Group.new("Italic", c.none, c.none, italics)
Group.new("Keyword", c.hue_5, c.none, style.NONE)
Group.new("Label", c.hue_3, c.none, style.NONE)
Group.new("LineNr", c.Gray:dark(), c.none, style.NONE)
Group.new("Macro", c.hue_3, c.none, style.NONE)
Group.new("MatchParen", c.hue_5, c.syntax_cursor, style.underline + style.bold)
Group.new("ModeMsg", c.White, c.none, style.NONE)
Group.new("MoreMsg", c.White, c.none, style.NONE)
Group.new("NonText", c.Gray, c.none, style.NONE)
Group.new("Normal", c.White, c.syntax_bg, style.NONE)
Group.new("Number", c.hue_6, c.none, style.NONE)
Group.new("Operator", c.syntax_accent, c.none, style.NONE)
Group.new("PMenu", c.none, c.pmenu, style.NONE)
Group.new("PMenuSbar", c.none, c.Gray, style.NONE)
Group.new("PMenuSel", c.none, c.Gray:dark(), style.NONE)
Group.new("PMenuThumb", c.none, c.White, style.NONE)
Group.new("PreCondit", c.hue_6_2, c.none, style.NONE)
Group.new("PreProc", c.hue_6_2, c.none, style.NONE)
Group.new("Question", c.hue_2, c.none, style.NONE)
Group.new("Repeat", c.hue_3, c.none, style.NONE)
Group.new("Search", c.Gray, c.hue_6_2, style.NONE)
Group.new("SignColumn", c.none, c.none, style.NONE)
Group.new("Special", c.hue_2, c.none, style.NONE)
Group.new("Special", c.hue_2, c.none, style.NONE)
Group.new("SpecialChar", c.none, c.none, style.NONE)
Group.new("SpecialComment", c.none, c.none, style.NONE)
Group.new("SpecialKey", c.special_grey, c.none, style.NONE)
Group.new("Statement", c.hue_3, c.none, style.NONE)
Group.new("StatusLine", c.White, c.none, style.NONE)
Group.new("StatusLineNC", c.Gray, c.none, style.NONE)
Group.new("StorageClass", c.hue_6_2, c.none, style.NONE)
Group.new("String", c.hue_4, c.none, style.NONE)
Group.new("Structure", c.hue_6_2, c.none, style.NONE)
Group.new("TabLine", c.Gray:light(), c.visual_grey, style.NONE)
Group.new("TabLineFill", c.Gray, c.visual_grey, style.NONE)
Group.new("TabLineSel", c.Gray, c.hue_2, style.NONE)
Group.new("Tag", c.none, c.none, style.NONE)
Group.new("Title", c.White, c.none, style.bold)
Group.new("Todo", c.hue_3, c.Gray, style.NONE)
Group.new("TooLong", c.hue_5, c.none, style.NONE)
Group.new("Type", c.hue_6_2, c.none, style.NONE)
Group.new("Typedef", c.hue_6_2, c.none, style.NONE)
Group.new("Underlined", c.none, c.none, style.underline)
Group.new("VertSplit", c.vertsplit, c.none, style.NONE)
Group.new("Visual", c.none, c.visual_grey, style.NONE)
Group.new("VisualNOS", c.none, c.visual_grey, style.NONE)
Group.new("WarningMsg", c.hue_5, c.none, style.NONE)
Group.new("Whitespace", c.special_grey, c.none, style.NONE)
Group.new("WildMenu", c.White, c.Gray, style.NONE)
Group.new("bold", c.none, c.none, style.bold)

Group.new("vimCommand", c.hue_3, c.none, style.NONE)
Group.new("vimCommentTitle", c.Gray, c.none, style.bold)
Group.new("vimFunction", c.hue_1, c.none, style.NONE)
Group.new("vimFuncName", c.hue_3, c.none, style.NONE)
Group.new("vimHighlight", c.hue_2, c.none, style.NONE)
Group.new("vimLineComment", c.Gray, c.none, italics)
Group.new("vimParenSep", c.Gray:light(), c.none, style.NONE)
Group.new("vimSep", c.Gray:light(), c.none, style.NONE)
Group.new("vimUserFunc", c.hue_1, c.none, style.NONE)
Group.new("vimVar", c.hue_5, c.none, style.NONE)

-- Spelling
Group.new("SpellBad", c.customSpell, c.none, style.undercurl)
Group.new("SpellLocal", c.Gray, c.none, style.undercurl)
Group.new("SpellCap", c.Gray, c.none, style.undercurl)
Group.new("SpellRare", c.Gray, c.none, style.undercurl)

-----------------------------
-- TreeSitter Highlighting --
-----------------------------
Group.new("TSAnnotation", c.hue_6_2, c.none, style.NONE)
Group.new("TSAttribute", c.hue_1, c.none, style.NONE)
Group.new("TSBoolean", c.hue_6, c.none, style.NONE)
Group.new("TSCharacter", c.hue_4, c.none, style.NONE)
Group.new("TSConditional", c.pink, c.none, style.NONE)
Group.new("TSConstBuiltin", c.hue_6, c.none, style.NONE)
Group.new("TSConstMacro", c.hue_1, c.none, style.NONE)
Group.new("TSConstant", c.hue_2, c.none, style.NONE)
Group.new("TSConstructor", c.hue_1, c.none, style.bold)
Group.new("TSEmphasis", c.RedBright, c.none, style.NONE)
Group.new("TSError", c.hue_5, c.none, style.NONE)
Group.new("TSException", c.pink, c.none, style.NONE)
Group.new("TSField", c.hue_5, c.none, style.NONE)
Group.new("TSFloat", c.hue_4, c.none, style.NONE)
Group.new("TSFuncBuiltin", c.hue_2, c.none, style.NONE)
Group.new("TSFuncMacro", c.hue_6_2, c.none, style.NONE)
Group.new("TSFunction", c.hue_2, c.none, style.bold)
Group.new("TSInclude", c.pink, c.none, style.bold) -- imports
Group.new("TSKeyword", c.pink, c.none, style.bold)
Group.new("TSKeywordFunction", c.pink, c.none, style.bold)
Group.new("TSKeywordOperator", c.pink, c.none, style.NONE)
Group.new("TSLabel", c.hue_2, c.none, style.NONE)
Group.new("TSLiteral", c.hue_6_2, c.none, style.NONE)
Group.new("TSMethod", c.hue_2, c.none, style.bold)
Group.new("TSNamespace", c.pink, c.none, style.bold)
Group.new("TSNumber", c.hue_6, c.none, style.NONE)
Group.new("TSOperator", c.White, c.none, style.NONE)
Group.new("TSParameter", c.hue_1, c.none, style.NONE)
Group.new("TSParameterReference", c.hue_1, c.none, style.NONE)
Group.new("TSProperty", c.hue_6_2, c.none, style.bold)
Group.new("TSPunctBracket", c.White, c.none, style.NONE)
Group.new("TSPunctDelimiter", c.White, c.none, style.NONE)
Group.new("TSPunctSpecial", c.Pink, c.none, style.bold)
Group.new("TSPunctSpecial", c.White, c.none, style.NONE)
Group.new("TSRepeat", c.pink, c.none, style.NONE)
Group.new("TSString", c.hue_4, c.none, style.NONE)
Group.new("TSStringEscape", c.hue_1, c.none, style.NONE)
Group.new("TSStringRegex", c.hue_4, c.none, style.NONE)
Group.new("TSStrong", c.RedBright, c.none, style.NONE)
Group.new("TSStructure", c.hue_6_2, c.none, style.NONE)
Group.new("TSTag", c.hue_5, c.none, style.NONE)
Group.new("TSTagDelimiter", c.Gray, c.none, style.NONE)
Group.new("TSText", c.hue_6_2, c.none, style.NONE)
Group.new("TSTitle", c.Green, c.none, style.bold)
Group.new("TSType", c.hue_2, c.none, style.bold)
Group.new("TSTypeBuiltin", c.hue_2, c.none, style.NONE)
Group.new("TSURI", c.Hint, c.none, style.NONE)
Group.new("TSUnderline", c.hue_6_2, c.none, style.NONE)
Group.new("TSVariable", c.hue_1, c.none, style.NONE)
Group.new("TSVariableBuiltin", c.hue_6_2, c.none, style.bold)

---------------------------
-- Filetype Highlighting --
---------------------------

-- Python
Group.new("pythonImport", c.hue_3, c.none, style.bold)
Group.new("pythonBuiltin", c.hue_1, c.none, style.NONE)
Group.new("pythonStatement", c.hue_3, c.none, style.bold)
Group.new("pythonParam", c.hue_6, c.none, style.NONE)
Group.new("pythonEscape", c.hue_5, c.none, style.NONE)
Group.new("pythonSelf", c.Gray:light(), c.none, italics)
Group.new("pythonClass", c.hue_2, c.none, style.NONE)
Group.new("pythonOperator", c.hue_3, c.none, style.NONE)
Group.new("pythonEscape", c.hue_5, c.none, style.NONE)
Group.new("pythonFunction", c.hue_2, c.none, style.NONE)
Group.new("pythonKeyword", c.hue_2, c.none, style.NONE)
Group.new("pythonModule", c.hue_3, c.none, style.NONE)
Group.new("pythonStringDelimiter", c.hue_4, c.none, style.NONE)
Group.new("pythonSymbol", c.hue_1, c.none, style.NONE)

-- Markdown
Group.new("markdownBold", c.Yellow, c.none, style.bold)
Group.new("markdownCode", c.Green, c.none, style.NONE)
Group.new("markdownCodeBlock", c.Orange, c.none, style.NONE)
Group.new("markdownCodeDelimiter", c.RedBright, c.none, style.NONE)
Group.new("markdownH1", c.Blue, c.none, style.bold)
Group.new("markdownH2", c.Blue, c.none, style.bold)
Group.new("markdownH3", c.Blue, c.none, style.bold)
Group.new("markdownH4", c.Blue, c.none, style.NONE)
Group.new("markdownH5", c.Blue, c.none, style.NONE)
Group.new("markdownH6", c.Blue, c.none, style.NONE)
Group.new("markdownHeadingDelimiter", c.Green, c.none, style.NONE)
Group.new("markdownLinkText", c.Green, c.none, style.NONE)
Group.new("markdownItalic", c.hue_6, c.none, italics)
Group.new("markdownListMarker", c.pink, c.none, style.bold)
Group.new("markdownUrl", c.Gray, c.none, style.NONE)

-- JSON
Group.new("jsonCommentError", c.White, c.none, style.NONE)
Group.new("jsonKeyword", c.hue_5, c.none, style.NONE)
Group.new("jsonQuote", c.Gray, c.none, style.NONE)
Group.new("jsonTrailingCommaError", c.hue_5, c.none, style.reverse)
Group.new("jsonMissingCommaError", c.hue_5, c.none, style.reverse)
Group.new("jsonNoQuotesError", c.hue_5, c.none, style.reverse)
Group.new("jsonNumError", c.hue_5, c.none, style.reverse)
Group.new("jsonString", c.hue_4, c.none, style.NONE)
Group.new("jsonBoolean", c.hue_3, c.none, style.NONE)
Group.new("jsonNumber", c.hue_6, c.none, style.NONE)
Group.new("jsonStringSQError", c.hue_5, c.none, style.reverse)
Group.new("jsonSemicolonError", c.hue_5, c.none, style.reverse)

-- Asciidoc
Group.new("asciidocListingBlock", c.Gray:light(), c.none, style.NONE)

-- C/C++ highlighting
Group.new("cInclude", c.hue_3, c.none, style.NONE)
Group.new("cPreCondit", c.hue_3, c.none, style.NONE)
Group.new("cPreConditMatch", c.hue_3, c.none, style.NONE)
Group.new("cType", c.hue_3, c.none, style.NONE)
Group.new("cStorageClass", c.hue_3, c.none, style.NONE)
Group.new("cStructure", c.hue_3, c.none, style.NONE)
Group.new("cOperator", c.hue_3, c.none, style.NONE)
Group.new("cStatement", c.hue_3, c.none, style.NONE)
Group.new("cTODO", c.hue_3, c.none, style.NONE)
Group.new("cConstant", c.hue_6, c.none, style.NONE)
Group.new("cSpecial", c.hue_1, c.none, style.NONE)
Group.new("cSpecialCharacter", c.hue_1, c.none, style.NONE)
Group.new("cString", c.hue_4, c.none, style.NONE)
Group.new("cppType", c.hue_3, c.none, style.NONE)
Group.new("cppStorageClass", c.hue_3, c.none, style.NONE)
Group.new("cppStructure", c.hue_3, c.none, style.NONE)
Group.new("cppModifier", c.hue_3, c.none, style.NONE)
Group.new("cppOperator", c.hue_3, c.none, style.NONE)
Group.new("cppAccess", c.hue_3, c.none, style.NONE)
Group.new("cppStatement", c.hue_3, c.none, style.NONE)
Group.new("cppConstant", c.hue_5, c.none, style.NONE)
Group.new("cCppString", c.hue_4, c.none, style.NONE)

-- CSS/Sass
Group.new("cssAttrComma", c.hue_3, c.none, style.NONE)
Group.new("cssAttributeSelector", c.hue_4, c.none, style.NONE)
Group.new("cssBraces", c.Gray:light(), c.none, style.NONE)
Group.new("cssClassName", c.hue_6, c.none, style.NONE)
Group.new("cssClassNameDot", c.hue_6, c.none, style.NONE)
Group.new("cssDefinition", c.hue_3, c.none, style.NONE)
Group.new("cssFontAttr", c.hue_6, c.none, style.NONE)
Group.new("cssFontDescriptor", c.hue_3, c.none, style.NONE)
Group.new("cssFunctionName", c.hue_2, c.none, style.NONE)
Group.new("cssIdentifier", c.hue_2, c.none, style.NONE)
Group.new("cssImportant", c.hue_3, c.none, style.NONE)
Group.new("cssInclude", c.White, c.none, style.NONE)
Group.new("cssIncludeKeyword", c.hue_3, c.none, style.NONE)
Group.new("cssMediaType", c.hue_6, c.none, style.NONE)
Group.new("cssProp", c.hue_1, c.none, style.NONE)
Group.new("cssPseudoClassId", c.hue_6, c.none, style.NONE)
Group.new("cssSelectorOp", c.hue_3, c.none, style.NONE)
Group.new("cssSelectorOp2", c.hue_3, c.none, style.NONE)
Group.new("cssStringQ", c.hue_4, c.none, style.NONE)
Group.new("cssStringQQ", c.hue_4, c.none, style.NONE)
Group.new("cssTagName", c.hue_5, c.none, style.NONE)
Group.new("cssAttr", c.hue_6, c.none, style.NONE)
Group.new("sassAmpersand", c.hue_5, c.none, style.NONE)
Group.new("sassClass", c.hue_6_2, c.none, style.NONE)
Group.new("sassControl", c.hue_3, c.none, style.NONE)
Group.new("sassExtend", c.hue_3, c.none, style.NONE)
Group.new("sassFor", c.White, c.none, style.NONE)
Group.new("sassProperty", c.hue_1, c.none, style.NONE)
Group.new("sassFunction", c.hue_1, c.none, style.NONE)
Group.new("sassId", c.hue_2, c.none, style.NONE)
Group.new("sassInclude", c.hue_3, c.none, style.NONE)
Group.new("sassMedia", c.hue_3, c.none, style.NONE)
Group.new("sassMediaOperators", c.White, c.none, style.NONE)
Group.new("sassMixin", c.hue_3, c.none, style.NONE)
Group.new("sassMixinName", c.hue_2, c.none, style.NONE)
Group.new("sassMixing", c.hue_3, c.none, style.NONE)
Group.new("scssSelectorName", c.hue_6_2, c.none, style.NONE)

-- Git and git related plugins
Group.new("gitcommitComment", c.Gray, c.none, style.NONE)
Group.new("gitcommitUnmerged", c.hue_4, c.none, style.NONE)
Group.new("gitcommitOnBranch", c.none, c.none, style.NONE)
Group.new("gitcommitBranch", c.hue_3, c.none, style.NONE)
Group.new("gitcommitDiscardedType", c.hue_5, c.none, style.NONE)
Group.new("gitcommitSelectedType", c.hue_4, c.none, style.NONE)
Group.new("gitcommitHeader", c.none, c.none, style.NONE)
Group.new("gitcommitUntrackedFile", c.hue_1, c.none, style.NONE)
Group.new("gitcommitDiscardedFile", c.hue_5, c.none, style.NONE)
Group.new("gitcommitSelectedFile", c.hue_4, c.none, style.NONE)
Group.new("gitcommitUnmergedFile", c.hue_6_2, c.none, style.NONE)
Group.new("gitcommitFile", c.none, c.none, style.NONE)
Group.new("gitcommitNoBranch", g.gitcommitBranch, g.gitcommitBranch, g.gitcommitBranch)
Group.new("gitcommitUntracked", g.gitcommitComment, g.gitcommitComment, g.gitcommitComment)
Group.new("gitcommitDiscarded", g.gitcommitComment, g.gitcommitComment, g.gitcommitComment)
Group.new("gitcommitDiscardedArrow", g.gitcommitDiscardedFile, g.gitcommitDiscardedFile, g.gitcommitDiscardedFile)
Group.new("gitcommitSelectedArrow", g.gitcommitSelectedFile, g.gitcommitSelectedFile, g.gitcommitSelectedFile)
Group.new("gitcommitUnmergedArrow", g.gitcommitUnmergedFile, g.gitcommitUnmergedFile, g.gitcommitUnmergedFile)
Group.new("SignifySignAdd", c.hue_4, c.none, style.NONE)
Group.new("SignifySignChange", c.hue_6_2, c.none, style.NONE)
Group.new("SignifySignDelete", c.hue_5, c.none, style.NONE)
Group.new("GitGutterAdd", g.SignifySignAdd, g.SignifySignAdd, g.SignifySignAdd)
Group.new("GitGutterChange", g.SignifySignChange, g.SignifySignChange, g.SignifySignChange)
Group.new("GitGutterDelete", g.SignifySignDelete, g.SignifySignDelete, g.SignifySignDelete)
Group.new("diffAdded", c.hue_4, c.none, style.NONE)
Group.new("diffRemoved", c.hue_5, c.none, style.NONE)

-- Go
Group.new("goDeclaration", c.hue_3, c.none, style.NONE)
Group.new("goField", c.hue_5, c.none, style.NONE)
Group.new("goMethod", c.hue_1, c.none, style.NONE)
Group.new("goType", c.hue_3, c.none, style.NONE)
Group.new("goUnsignedInts", c.hue_1, c.none, style.NONE)

-- Haskell highlighting
Group.new("haskellDeclKeyword", c.hue_2, c.none, style.NONE)
Group.new("haskellType", c.hue_4, c.none, style.NONE)
Group.new("haskellWhere", c.hue_5, c.none, style.NONE)
Group.new("haskellImportKeywords", c.hue_2, c.none, style.NONE)
Group.new("haskellOperators", c.hue_5, c.none, style.NONE)
Group.new("haskellDelimiter", c.hue_2, c.none, style.NONE)
Group.new("haskellIdentifier", c.hue_6, c.none, style.NONE)
Group.new("haskellKeyword", c.hue_5, c.none, style.NONE)
Group.new("haskellNumber", c.hue_1, c.none, style.NONE)
Group.new("haskellString", c.hue_1, c.none, style.NONE)

-- HTML
Group.new("htmlArg", c.hue_6, c.none, style.NONE)
Group.new("htmlTagName", c.hue_5, c.none, style.NONE)
Group.new("htmlTagN", c.hue_5, c.none, style.NONE)
Group.new("htmlSpecialTagName", c.hue_5, c.none, style.NONE)
Group.new("htmlTag", c.Gray:light(), c.none, style.NONE)
Group.new("htmlEndTag", c.Gray:light(), c.none, style.NONE)
Group.new("MatchTag", c.hue_5, c.syntax_cursor, style.underline + style.bold)

-- JavaScript
Group.new("coffeeString", c.hue_4, c.none, style.NONE)
Group.new("javaScriptBraces", c.Gray:light(), c.none, style.NONE)
Group.new("javaScriptFunction", c.hue_3, c.none, style.NONE)
Group.new("javaScriptIdentifier", c.hue_3, c.none, style.NONE)
Group.new("javaScriptNull", c.hue_6, c.none, style.NONE)
Group.new("javaScriptNumber", c.hue_6, c.none, style.NONE)
Group.new("javaScriptRequire", c.hue_1, c.none, style.NONE)
Group.new("javaScriptReserved", c.hue_3, c.none, style.NONE)
-- httpc.//github.com/pangloss/vim-javascript
Group.new("jsArrowFunction", c.hue_3, c.none, style.NONE)
Group.new("jsBraces", c.Gray:light(), c.none, style.NONE)
Group.new("jsClassBraces", c.Gray:light(), c.none, style.NONE)
Group.new("jsClassKeywords", c.hue_3, c.none, style.NONE)
Group.new("jsDocParam", c.hue_2, c.none, style.NONE)
Group.new("jsDocTags", c.hue_3, c.none, style.NONE)
Group.new("jsFuncBraces", c.Gray:light(), c.none, style.NONE)
Group.new("jsFuncCall", c.hue_2, c.none, style.NONE)
Group.new("jsFuncParens", c.Gray:light(), c.none, style.NONE)
Group.new("jsFunction", c.hue_3, c.none, style.NONE)
Group.new("jsGlobalObjects", c.hue_6_2, c.none, style.NONE)
Group.new("jsModuleWords", c.hue_3, c.none, style.NONE)
Group.new("jsModules", c.hue_3, c.none, style.NONE)
Group.new("jsNoise", c.Gray:light(), c.none, style.NONE)
Group.new("jsNull", c.hue_6, c.none, style.NONE)
Group.new("jsOperator", c.hue_3, c.none, style.NONE)
Group.new("jsParens", c.Gray:light(), c.none, style.NONE)
Group.new("jsStorageClass", c.hue_3, c.none, style.NONE)
Group.new("jsTemplateBraces", c.hue_5_2, c.none, style.NONE)
Group.new("jsTemplateVar", c.hue_4, c.none, style.NONE)
Group.new("jsThis", c.hue_5, c.none, style.NONE)
Group.new("jsUndefined", c.hue_6, c.none, style.NONE)
Group.new("jsObjectValue", c.hue_2, c.none, style.NONE)
Group.new("jsObjectKey", c.hue_1, c.none, style.NONE)
Group.new("jsReturn", c.hue_3, c.none, style.NONE)
-- httpc.//github.com/othree/yajs.vim
Group.new("javascriptArrowFunc", c.hue_3, c.none, style.NONE)
Group.new("javascriptClassExtends", c.hue_3, c.none, style.NONE)
Group.new("javascriptClassKeyword", c.hue_3, c.none, style.NONE)
Group.new("javascriptDocNotation", c.hue_3, c.none, style.NONE)
Group.new("javascriptDocParamName", c.hue_2, c.none, style.NONE)
Group.new("javascriptDocTags", c.hue_3, c.none, style.NONE)
Group.new("javascriptEndColons", c.Gray, c.none, style.NONE)
Group.new("javascriptExport", c.hue_3, c.none, style.NONE)
Group.new("javascriptFuncArg", c.White, c.none, style.NONE)
Group.new("javascriptFuncKeyword", c.hue_3, c.none, style.NONE)
Group.new("javascriptIdentifier", c.hue_5, c.none, style.NONE)
Group.new("javascriptImport", c.hue_3, c.none, style.NONE)
Group.new("javascriptObjectLabel", c.White, c.none, style.NONE)
Group.new("javascriptOpSymbol", c.hue_1, c.none, style.NONE)
Group.new("javascriptOpSymbols", c.hue_1, c.none, style.NONE)
Group.new("javascriptPropertyName", c.hue_4, c.none, style.NONE)
Group.new("javascriptTemplateSB", c.hue_5_2, c.none, style.NONE)
Group.new("javascriptVariable", c.hue_3, c.none, style.NONE)

-- PureScript
Group.new("purescriptKeyword", c.hue_3, c.none, style.NONE)
Group.new("purescriptModuleName", c.White, c.none, style.NONE)
Group.new("purescriptIdentifier", c.White, c.none, style.NONE)
Group.new("purescriptType", c.hue_6_2, c.none, style.NONE)
Group.new("purescriptTypeVar", c.hue_5, c.none, style.NONE)
Group.new("purescriptConstructor", c.hue_5, c.none, style.NONE)
Group.new("purescriptOperator", c.White, c.none, style.NONE)

-- Ruby
Group.new("rubyBlock", c.hue_3, c.none, style.NONE)
Group.new("rubyBlockParameter", c.hue_5, c.none, style.NONE)
Group.new("rubyBlockParameterList", c.hue_5, c.none, style.NONE)
Group.new("rubyCapitalizedMethod", c.hue_3, c.none, style.NONE)
Group.new("rubyClass", c.hue_3, c.none, style.NONE)
Group.new("rubyConstant", c.hue_6_2, c.none, style.NONE)
Group.new("rubyControl", c.hue_3, c.none, style.NONE)
Group.new("rubyDefine", c.hue_3, c.none, style.NONE)
Group.new("rubyEscape", c.hue_5, c.none, style.NONE)
Group.new("rubyFunction", c.hue_2, c.none, style.NONE)
Group.new("rubyGlobalVariable", c.hue_5, c.none, style.NONE)
Group.new("rubyInclude", c.hue_2, c.none, style.NONE)
Group.new("rubyIncluderubyGlobalVariable", c.hue_5, c.none, style.NONE)
Group.new("rubyInstanceVariable", c.hue_5, c.none, style.NONE)
Group.new("rubyInterpolation", c.hue_1, c.none, style.NONE)
Group.new("rubyInterpolationDelimiter", c.hue_5, c.none, style.NONE)
Group.new("rubyKeyword", c.hue_2, c.none, style.NONE)
Group.new("rubyModule", c.hue_3, c.none, style.NONE)
Group.new("rubyPseudoVariable", c.hue_5, c.none, style.NONE)
Group.new("rubyRegexp", c.hue_1, c.none, style.NONE)
Group.new("rubyRegexpDelimiter", c.hue_1, c.none, style.NONE)
Group.new("rubyStringDelimiter", c.hue_4, c.none, style.NONE)
Group.new("rubySymbol", c.hue_1, c.none, style.NONE)

-- XML
Group.new("xmlAttrib", c.hue_6_2, c.none, style.NONE)
Group.new("xmlEndTag", c.hue_5, c.none, style.NONE)
Group.new("xmlTag", c.hue_5, c.none, style.NONE)
Group.new("xmlTagName", c.hue_5, c.none, style.NONE)

-- ZSH
Group.new("zshCommands", c.White, c.none, style.NONE)
Group.new("zshDeref", c.hue_5, c.none, style.NONE)
Group.new("zshShortDeref", c.hue_5, c.none, style.NONE)
Group.new("zshFunction", c.hue_1, c.none, style.NONE)
Group.new("zshKeyword", c.hue_3, c.none, style.NONE)
Group.new("zshSubst", c.hue_5, c.none, style.NONE)
Group.new("zshSubstDelim", c.Gray, c.none, style.NONE)
Group.new("zshTypes", c.hue_3, c.none, style.NONE)
Group.new("zshVariableDef", c.hue_6, c.none, style.NONE)

-- Rust
Group.new("rustExternCrate", c.hue_5, c.none, style.bold)
Group.new("rustIdentifier", c.hue_2, c.none, style.NONE)
Group.new("rustDeriveTrait", c.hue_4, c.none, style.NONE)
Group.new("SpecialComment", c.Gray, c.none, style.NONE)
Group.new("rustCommentLine", c.Gray, c.none, style.NONE)
Group.new("rustCommentLineDoc", c.Gray, c.none, style.NONE)
Group.new("rustCommentLineDocError", c.Gray, c.none, style.NONE)
Group.new("rustCommentBlock", c.Gray, c.none, style.NONE)
Group.new("rustCommentBlockDoc", c.Gray, c.none, style.NONE)
Group.new("rustCommentBlockDocError", c.Gray, c.none, style.NONE)

-- Man
Group.new("manTitle", g.String, g.String, g.String)
Group.new("manFooter", c.Gray, c.none, style.NONE)
