#!/bin/bash

ln -sf ~/.files/Code/User/keybindings.json ~/.config/Code/User/keybindings.json
ln -sf ~/.files/Code/User/settings.json ~/.config/Code/User/settings.json
ln -sf ~/.files/Code/User/snippets  ~/.config/Code/User
echo "Created links for keybindings.json, settings.json and snippets"
