#!/bin/bash
# docs.nvidia.com/cuda/cuda-installation-guide-linux

# Check to verify Cuda-Capable GPU
echo "-------------------------------------------------"
echo "Check to verify Cuda-Capable GPU..."
lspci | grep -i nvidia

echo "VGA compatible controller ?"


# Check if system has gcc installed.
echo "-------------------------------------------------"
echo "Check if system has gcc installed"
gcc --version

# verify correct headers
echo "-------------------------------------------------"
echo "Verify correct headers" 
uname -r
sudo apt-get install linux-headers-$(uname -r)

echo "-------------------------------------------------"
echo "sudo apt-get nvidia-375 nvidia-modprobe"
sudo apt-get install nvidia-375 nvidia-modprobe
echo "-------------------------------------------------"
echo "Please Restart Computer"


# CUDA
echo "Downloading CUDA_8.0.61_375.26 files"
cd ~ 
wget https://developer.nvidia.com/compute/cuda/8.0/Prod2/local_installers/cuda_8.0.61_375.26_linux-run
chmod +x cuda_8.0.61_375.26_linux-run
./cuda_8.0.61_375.26_linux-run --extract=$HOME
sudo ./cuda-linux64-rel-8.0.61-21551265.run

# After installation configure runtime library
sudo bash -c "echo /usr/local/cuda/lib64/ > /etc/ld.so.conf.d/cuda.conf"
sudo ldconfig

# It is also recommended for Ubuntu users to append string /usr/local/cuda/bin to system file /etc/environments so that nvcc will be included in $PATH. This will take effect after reboot.
# append /usr/local/cuda/bin to the end of PATH-variable
sudo vim /etc/environment
/usr/local/cuda/bin

# from nvidia guide
export PATH=/usr/local/cuda-8.0/bin${PATH:+:${PATH}}

# cuDNN install
#       http://docs.nvidia.com/deeplearning/sdk/cudnn-install/index.html#prerequisites

# Download Tar file from webpage
tar -xzvf cudnn-8.0-linux-x64-v7.tgz


