swipe:
    3: 
        left: 
            shortcut: 'super+l'
        right: 
            shortcut: 'super+h'
        up: 
            shortcut: 'super+j'
        down: 
            shortcut: 'super+k'
    4:
        left: 
            shortcut: 'alt+Right'
        right: 
            shortcut: 'alt+Left'
        up: 
            shortcut: 'super+Up'
        down: 
            shortcut: 'super+Down'
pinch:
    in:
        shortcut: 'ctrl+plus'
    out:
        shortcut: 'ctrl+minus'
threshold:
    swipe: 1
    pinch: 1

interval:
    swipe: 1
    pinch: 1
