#!/bin/bash
current=$(cat /sys/class/backlight/intel_backlight/brightness)
T=2000
Img="/home/erik/.files/icons/brightness_yellow.png"
if [[ $current == 500 ]]; then
    bright=937
    echo $bright > /sys/class/backlight/intel_backlight/brightness
elif [[ $current == 937 ]]; then
    bright=100
    echo $bright > /sys/class/backlight/intel_backlight/brightness
elif [[ $current == 100 ]]; then
    bright=500
    echo $bright > /sys/class/backlight/intel_backlight/brightness
else
    bright=$current
fi
killall notify-osd
DISPLAY=:0 notify-send -t $T --urgency=normal --icon=$Img "Intel: $bright"
