#!/bin/bash

echo "Link tmuxinator projects ~/.config/tmuxinator"
ln -sf $HOME/.files/tmuxinator/projects ~/.config/tmuxinator

# https://stackoverflow.com/questions/14505047/loop-through-all-the-files-with-a-specific-extension
# cd ~/.files/tmuxinator
# echo "Creating ~/.config/tmuxinator folder and link .yml files"
# mkdir -p ~/.config/tmuxinator
# shopt -s nullglob
# for i in *.yml; do
# 	echo "$(realpath $i)"
# 	ln -sf "$(realpath $i)" ~/.config/tmuxinator
# done
# echo Done!

