#!/bin/python

import os

fp = "~/Documents/Papers"
papers = []
for files, dir, root in os.walk(fp):
    for f in files:
        if f.endswith(".pdf"):
            papers.append(f)


FILE=$( echo -e $list | rofi -dmenu -i -p 'Papers: ' )

Img=~/.files/icons/icons/check_green.png
if [ -f $FILE ]; then
    #File exists, open file
    DISPLAY=:0 notify-send -t 3000 --urgency=critical --icon=$Img "Opening $FILE"

    urxvt -e bash -c "stty -ixon && vim $FILE" &
else
    ans=$( echo -e "Yes \n No" | rofi -dmenu -i -p "Wish to create $FILE ? " )
    if [ $ans == 'Yes' ]; then
        # Safety check
        cp ~/Documents/latex/LaTeX/Note_base.tex ~/Documents/latex/Notes/"$FILE"

        DISPLAY=:0 notify-send -t 3000 --urgency=critical --icon=$Img "Created $FILE"

        urxvt -e bash -c "stty -ixon && vim $FILE" &
    else
        exit 1
    fi
fi



