#!/bin/bash
echo "########################################################"
echo
echo                Downloading Anaconda
cd ~/Downloads
wget https://repo.continuum.io/archive/Anaconda3-4.4.0-Linux-x86_64.sh
chmod +x Anaconda3-4.4.0-Linux-x86_64.sh
echo "########################################################"
echo
echo                Installing Anaconda
sudo -u erik bash -c './Anaconda3-4.4.0-Linux-x86_64.sh'
echo "########################################################"
echo
echo "               Downgrading ipython (for slimux)"
pip install --upgrade --force-reinstall ipython==4.2.1                                                                                                                          <<<
echo "########################################################"
echo "                      Done!"
echo "########################################################"
echo "Installing pytorch with cuda support" 
conda install pytorch torchvision cuda80 -c soumith
echo "########################################################"
echo "                      Done!"
echo "########################################################"
echo "Installing tqdm"
conda install tqdm
echo "########################################################"
echo "                      Done!"
echo "########################################################"




