#!/bin/bash
# Upgrading
echo Upgrading "(apt-get update/upgrade/dist-upgrade)"
echo "########################################################"
echo "########################################################"
# -qq will not show anything in terminal
# -yy will answer yes to everything even if errors
echo                Update  
sudo apt-get update -yyqq 
echo "########################################################"
echo "########################################################"
echo                Upgrade
sudo apt-get upgrade -yyqq
echo "########################################################"
echo "########################################################"
echo                Dist-upgrade
sudo apt-get dist-upgrade -yyqq

# Install needed programs
echo "########################################################"
echo "########################################################"
echo "########################################################"
echo "########################################################"
echo            Installing programs "(git/tmux and the like...)"
sudo apt-get install -yyqq git tmux htop xclip\
    zsh feh curl unclutter vim-gtk udiskie zathura\
    rxvt-unicode-256color ranger wget curl\
    autoconf gnome-session-bin python-pip\
    latexmk libappindicator1 wakeonlan \
    rofi xdotool
# notify-send, working version (otherwise the -t flag did not do anything)
# (with some extra functions recommended in solition to the above.
echo "########################################################"
echo            Additional installs for libnotify
sudo add-apt-repository ppa:leolik/leolik -yy
sudo add-apt-repository ppa:nilarimogard/webupd8 -yy
sudo apt-get update -yyqq
sudo apt-get install libnotify-bin -yy
sudo apt-get install notifyosdconfig -yy
pkill notify-osd

echo "########################################################"
echo "########################################################"
echo                        Done!
echo "########################################################"
echo 
echo                Installing chrome...
cd ~/Downloads
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg -i --force-depends google-chrome-stable_current_amd64.deb
sudo apt-get install -f -yyqq
sudo rm google-chrome-stable_current_amd64.deb
cd ~
echo "########################################################"
echo                        Done!
echo "########################################################"
echo 
echo                Installing Spotify...
# From spotify install guide
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys BBEBDCB318AD50EC6865090613B00F1FD2C19886 0DF731E45CE24F27EEEB1450EFDC8610341D9410
echo deb http://repository.spotify.com stable non-free | sudo tee /etc/apt/sources.list.d/spotify.list
sudo apt-get update -yyqq
sudo apt-get install spotify-client -yyqq
echo "########################################################"
echo                        Done!
############################################################################
echo "\n \n \n"
echo "########################################################"
echo "########################################################"
echo "########################################################"
echo "########################################################"
echo        Installing i3-gaps dependencies...
# i3 (From https://i3wm.org/docs/repositories.html)
sudo apt-get install -yyqq libxcb1-dev libxcb-keysyms1-dev \
    libpango1.0-dev libxcb-util0-dev libxcb-icccm4-dev \
    libyajl-dev libstartup-notification0-dev \
    libxcb-randr0-dev libev-dev libxcb-cursor-dev \
    libxcb-xinerama0-dev libxcb-xkb-dev libxkbcommon-dev \
    libxkbcommon-x11-dev autoconf libxcb-xrm-dev 
# extra dependency
sudo add-apt-repository ppa:aguignard/ppa -yy
sudo apt-get update -yyqq
sudo apt-get install libxcb-xrm-dev -yyqq
echo "########################################################"
echo "########################################################"
echo "########################################################"
echo "########################################################"
echo "########################################################"
echo "########################################################"
echo
echo                    Setting new shell to Zsh
sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
sudo -u erik chsh -s $(which zsh)

echo "########################################################"
echo "########################################################"
echo "########################################################"
echo "########################################################"
echo "########################################################"
echo
echo                    Installing i3...
sleep 2
sudo apt-get install i3 -yyq
echo "########################################################"
echo "########################################################"
echo "########################################################"
echo
echo                   i3 installed!  
echo
echo "########################################################"
echo "########################################################"
echo "########################################################"
echo            Create links for config files...
ln -sf ~/.files/vimrc ~/.vimrc
ln -sf ~/.files/zshrc ~/.zshrc
ln -sf ~/.files/inputrc ~/.inputrc
ln -sf ~/.files/bashrc ~/.bashrc
ln -sf ~/.files/tmux.conf ~/.tmux.conf
ln -sf ~/.files/gitignore ~/.gitignore
ln -sf ~/.files/gitconfig ~/.gitconfig
ln -sf ~/.files/xinitrc ~/.xinitrc
ln -sf ~/.files/Xresources ~/.Xresources
ln -sf ~/.files/Xdefaults ~/.Xdefaults
mkdir -p ~/.config/zathura
ln -sf ~/.files/zathurarc ~/.config/zathura/zathurarc
# i3
mkdir -p ~/.config/i3
ln -sf ~/.files/i3/i3status.conf ~/.config/i3/i3status.conf
ln -sf ~/.files/i3/config ~/.config/i3/config
# ranger
mkdir -p ~/.config/ranger
ln -sf ~/.files/ranger/rc.conf ~/.config/ranger/rc.conf
ln -sf ~/.files/ranger/rifle.conf ~/.config/ranger/rifle.conf
ln -sf ~/.files/ranger/scope.sh ~/.config/ranger/scope.sh
ln -sf ~/.files/ranger/commands.py ~/.config/ranger/commands.py
ln -sf ~/.files/ranger/colorschemes ~/.config/ranger/colorschemes
# Place wallpaper 
cp ~/.files/Wallpaper.png ~/.config/wall.png
echo
echo "#########################################################################"
echo                Done with linking!
echo
echo "########################################################"
echo            Restarting in 10 seconds
echo "########################################################"
echo            Please restart computer.
# sleep 1
# echo 9; sleep 1
# echo 8; sleep 1
# echo 7; sleep 1
# echo 6; sleep 1
# echo 5; sleep 1
# echo 4; sleep 1
# echo 3; sleep 1
# echo 2; sleep 1
# echo 1; sleep 1
# sudo shutdown -r 0
#

