#!/bin/bash

# Urxvt

# Resize font perl-script in a folder where urxvt looks.
cd /usr/lib/urxvt/perl
sudo wget https://raw.githubusercontent.com/simmel/urxvt-resize-font/master/resize-font

# Xrandr
xrandr --output [screen name] -s (--auto or HxW)--output [second screen] -s HxW

xrandr --output [screen name] -s (--auto or HxW)--output [second screen] --auto
