#!/bin/bash
# Installer for pywal
# Clones the repo into ~/Programs/pywal
mkdir -p ~/Programs && cd ~/Programs
git clone https://github.com/dylanaraps/pywal.git
echo Installing dependencies...
sudo apt-get install imagemagick feh -y
cd pywal
echo pip install..
pip install .
echo "pywal installation done"



