#!/bin/bash
# Require sudo right
# if [[ $UID != 0 ]]; then
#     echo "Please run this script with sudo :"
#     echo "sudo $0 $*"
#     exit 1
# fi
echo "########################################################"
echo "########################################################"
echo "########################################################"
echo "########################################################"
echo
echo            Installing vim plugins and color.
~/.files/Installation/install_scripts/Vim_plugin_install


echo "########################################################"
echo
echo Setting new shell to Zsh
wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh
sudo chsh -s `which zsh`

# Upgrading
echo Upgrading "(apt-get update/upgrade/dist-upgrade)"
sudo apt-get update
sudo apt-get upgrade -yyqq

echo "########################################################"
echo
echo                Downloading Anaconda
cd ~
wget https://repo.continuum.io/archive/Anaconda3-4.4.0-Linux-x86_64.sh
chmod +x Anaconda3-4.4.0-Linux-x86_64.sh
sudo -u erik bash -c './Anaconda3-4.4.0-Linux-x86_64.sh'
echo "########################################################"
echo
echo                Installing pywal
~/.files/Installation/install_scripts/pywal_install
echo "########################################################"
echo            Restarting in 10 seconds
echo "########################################################"
sleep 1
echo 9; sleep 1
echo 8; sleep 1
echo 7; sleep 1
echo 6; sleep 1
echo 5; sleep 1
echo 4; sleep 1
echo 3; sleep 1
echo 2; sleep 1
echo 1; sleep 1
sudo shutdown -r 0


