#!/usr/bin/python3

import os
from os.path import join, expanduser
import glob

HOME = expanduser('~')
src = join(HOME, '.files', 'firefox', 'userChrome.css')

dst = glob.glob(join(HOME, '.mozilla/firefox/**/chrome'))[0]
dst = join(dst, 'userChrome.css')

print(f'Creating link:\n {src} -> {dst}')

cmd = ' '.join(['ln -sf', src, dst])
os.system(cmd)

