#!/bin/bash

# Make a dmenu as in new_note to search for man pages directly without opennig terminal. Then open in terminal.
mdir=$(man --where --all)
for dir in $mdir; 
do
    cd dir
    for f in `ls`; 
        do
            list+="$f\n"
        done
done

echo $list
#FILE=$( echo -e $list | rofi -dmenu -i -p 'NOTES: ' )


