#!/bin/bash
cd ~/Documents/latex/Notes
for f in `ls *tex`; 
do
    list+="$f\n"
done
FILE=$( echo -e $list | rofi -dmenu -i -p 'NOTES: ' )

if [ -z "$FILE" ]; then
    exit 1
fi

Vim=~/.files/icons/vim-icon.png
if [ -f $FILE ]; then
    #File exists, open file
    DISPLAY=:0 notify-send -t 3000 --urgency=critical --icon=$Vim "Opening $FILE"
    urxvt -e bash -c "stty -ixon && vim $FILE" &
else
    ans=$( echo -e "Yes \n No" | rofi -dmenu -i -p "Wish to create $FILE ? " )
    if [ $ans == 'Yes' ]; then
        # Safety check
        cp ~/Documents/latex/LaTeX/Note_base.tex ~/Documents/latex/Notes/"$FILE"
        DISPLAY=:0 notify-send -t 3000 --urgency=critical --icon=$Vim "Created $FILE"
        urxvt -e bash -c "stty -ixon && vim $FILE" &
    else
        exit 1
    fi
fi



