#!/usr/bin/env python
import os
exists=False
with open('/home/erik/.config/xfce4/terminal/terminalrc') as f_in:
    with open('/home/erik/.config/xfce4/terminal/terminalrc_TMP','w') as f_out:
        for line in f_in:
            if "BackgroundDarkness" in line:
                exists=True
                f_out.write("BackgroundDarkness=0,"+str( (int(line[21])+1)%10 )+"\n")
            else:
                f_out.write(line)
        if not exists:
            f_out.write("BackgroundDarkness=0,5")
# rename files
os.rename('/home/erik/.config/xfce4/terminal/terminalrc', '/home/erik/.config/xfce4/terminal/terminalrc_old')
os.rename('/home/erik/.config/xfce4/terminal/terminalrc_TMP', '/home/erik/.config/xfce4/terminal/terminalrc')
