#! /bin/bash
# vim: ft=bash

echo "Create a dummy conf path '$HOME/.config.theme_override'"
mkdir $HOME/.config.theme_override

echo "Link the original Mendeley conf path to the dummy"
echo "ln -s '$HOME/.config.theme_override/Mendeley Ltd.'" "$HOME/.config/Mendeley Ltd."

ln -s "$HOME/.config.theme_override/Mendeley Ltd." "$HOME/.config/Mendeley Ltd."

echo "Change the application desktop file"

mv $HOME/.local/share/applications/mendeleydesktop.desktop $HOME/.local/share/applications/mendeleydesktop.desktop.BAK
cp $HOME/.files/misc/Mendeley/mendeleydesktop.desktop $HOME/.local/share/applications/mendeleydesktop.desktop

echo "Done"
